#include "dialog\content_sys.sqf";
disableSerialization;

_switch = _this select 0;

_dialog = findDisplay contentsys_DIALOG;
_contentList = _dialog displayCtrl content_list;

_contentListIndex = _contentList lbAdd format["1$ KORD_high"];
_contentList lbSetData [(lbSize _contentList)-1, "KORD_high"];
_contentListIndex = _contentList lbAdd format["2$ KORD"];
_contentList lbSetData [(lbSize _contentList)-1, "KORD"];
_contentListIndex = _contentList lbAdd format["3$ Land_Misc_deerstand"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_Misc_deerstand"];
_contentListIndex = _contentList lbAdd format["4$ Land_fortified_nest_big"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_fortified_nest_big"];
_contentListIndex = _contentList lbAdd format["5$ WarfareBCamp"];
_contentList lbSetData [(lbSize _contentList)-1, "WarfareBCamp"];
_contentListIndex = _contentList lbAdd format["6$ WarfareBDepot"];
_contentList lbSetData [(lbSize _contentList)-1, "WarfareBDepot"];
_contentListIndex = _contentList lbAdd format["7$ Land_fortified_nest_small"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_fortified_nest_small"];
_contentListIndex = _contentList lbAdd format["8$ Land_Fort_Watchtower"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_Fort_Watchtower"];
_contentListIndex = _contentList lbAdd format["9$ Land_GuardShed"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_GuardShed"];
_contentListIndex = _contentList lbAdd format["10$ MASH"];
_contentList lbSetData [(lbSize _contentList)-1, "MASH"];
_contentListIndex = _contentList lbAdd format["11$ Land_tent_east"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_tent_east"];
_contentListIndex = _contentList lbAdd format["12$ Land_fort_artillery_nest"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_fort_artillery_nest"];
_contentListIndex = _contentList lbAdd format["13$ Land_ConcreteRamp"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_ConcreteRamp"];
_contentListIndex = _contentList lbAdd format["14$ RampConcrete"];
_contentList lbSetData [(lbSize _contentList)-1, "RampConcrete"];
_contentListIndex = _contentList lbAdd format["15$ Land_fort_rampart"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_fort_rampart"];
_contentListIndex = _contentList lbAdd format["16$ Land_Misc_Scaffolding"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_Misc_Scaffolding"];
_contentListIndex = _contentList lbAdd format["17$ Land_leseni2x"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_leseni2x"];
_contentListIndex = _contentList lbAdd format["18$ Land_prebehlavka"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_prebehlavka"];
_contentListIndex = _contentList lbAdd format["19$ Land_CncBlock_Stripes"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_CncBlock_Stripes"];
_contentListIndex = _contentList lbAdd format["20$ Hhedgehog_concreteBig"];
_contentList lbSetData [(lbSize _contentList)-1, "Hhedgehog_concreteBig"];
_contentListIndex = _contentList lbAdd format["21$ Fort_Barricade"];
_contentList lbSetData [(lbSize _contentList)-1, "Fort_Barricade"];
_contentListIndex = _contentList lbAdd format["22$ Hedgehog"];
_contentList lbSetData [(lbSize _contentList)-1, "Hedgehog"];
_contentListIndex = _contentList lbAdd format["23$ Land_Misc_Cargo1D"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_Misc_Cargo1D"];
_contentListIndex = _contentList lbAdd format["24$ Fort_Crate_wood"];
_contentList lbSetData [(lbSize _contentList)-1, "Fort_Crate_wood"];
_contentListIndex = _contentList lbAdd format["24$ Concrete_Wall_EP1"];
_contentList lbSetData [(lbSize _contentList)-1, "Concrete_Wall_EP1"];
_contentListIndex = _contentList lbAdd format["26$ Land_ConcreteBlock"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_ConcreteBlock"];
_contentListIndex = _contentList lbAdd format["27$ Base_WarfareBBarrier10xTall"];
_contentList lbSetData [(lbSize _contentList)-1, "Base_WarfareBBarrier10xTall"];
_contentListIndex = _contentList lbAdd format["28$ Base_WarfareBBarrier10x"];
_contentList lbSetData [(lbSize _contentList)-1, "Base_WarfareBBarrier10x"];
_contentListIndex = _contentList lbAdd format["29$ Base_WarfareBBarrier5x"];
_contentList lbSetData [(lbSize _contentList)-1, "Base_WarfareBBarrier5x"];
_contentListIndex = _contentList lbAdd format["30$ Land_HBarrier_large"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_HBarrier_large"];
_contentListIndex = _contentList lbAdd format["31$ Fort_RazorWire"];
_contentList lbSetData [(lbSize _contentList)-1, "Fort_RazorWire"];
_contentListIndex = _contentList lbAdd format["32$ Land_fort_bagfence_corner"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_fort_bagfence_corner"];
_contentListIndex = _contentList lbAdd format["33$ Land_fort_bagfence_long"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_fort_bagfence_long"];
_contentListIndex = _contentList lbAdd format["34$ Land_fort_bagfence_round"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_fort_bagfence_round"];
_contentListIndex = _contentList lbAdd format["35$ Land_BagFenceLong"];
_contentList lbSetData [(lbSize _contentList)-1, "Land_BagFenceLong"];